version: '2'
services:
  service:
    image: dajare-service
    restart: always
    build: ./service
    environment:
        - PYTHONUNBUFFERED=1
    expose:
      - "5000"
    volumes:
      - static_file:/app/static
    command: pipenv run gunicorn --workers=2 --bind=0.0.0.0:5000 dajare:app
  model:
    image: tensorflow/serving
    ports:
      - "8038:8501"
    environment:
      - MODEL_NAME=EmotionFlow
    volumes:
      - ./models/EmotionFlow:/models/EmotionFlow
  nginx:
    image: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_file:/app/static
volumes:
  static_file:
