version: '2'
services:
  service:
    image: dajare-service
    restart: always
    build: ./service
    environment:
        - PYTHONUNBUFFERED=1
    expose:
      - "5000"
    command: pipenv run gunicorn --workers=2 --bind=0.0.0.0:5000 dajare:app
  nginx:
    image: nginx:latest
    restart: always
    container_name: production_nginx
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
     - ./.nginx/log/:/var/log/nginx/
     - ./.nginx/cache/:/etc/nginx/cache
     - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
     - 80:80
     - 443:443
volumes:
  model_info:
